server:
  port: 8762
  context-path: /cluecds
  tomcat:
          uri-encoding: UTF-8
          max-threads: 1000
          min-spare-threads: 30

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

spring:
  application:
    name: cluecds
  # 环境 dev|test|pro
  profiles:
      active: test
  # jackson时间格式化
  jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss
  freemarker:
      cache: false
  http:
      multipart:
          max-file-size: 100MB
          max-request-size: 100MB
          enabled: true
  redis:
      database: 0
      host: localhost
      port: 6379
      password:      # 密码（默认为空）
      timeout: 6000  # 连接超时时长（毫秒）
      pool:
          max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
          max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 10      # 连接池中的最大空闲连接
          min-idle: 5       # 连接池中的最小空闲连接

# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml
    configLocation: classpath:mybatis.xml


geo:
    redis:
        open: true  # 是否开启redis缓存  true开启   false关闭
    shiro:
        redis: false # true表示shiro session存到redis里，需要开启redis，才会生效【分布式场景】


logging:
  path: /tmp/apps/log/cluecds/